#!/bin/sh

integration_name="equifax_au"

pipenv run coverage run -m pytest && \
pipenv run coverage xml -i && \

sed -i "s/filename=\"/filename=\"${integration_name}\//g" coverage.xml && \

pipenv run codecov -F ${integration_name},unittests -X search -f coverage.xml
