default_setup: &default_setup
    - checkout
    - attach_workspace:
        at: workspace
    - add_ssh_keys:
        fingerprints:
            - "e4:b4:92:9b:6a:57:f5:8a:5d:ee:0a:29:b4:6a:cf:65"
    - run: sudo pip install pipenv

aliases:
    - &attach_to_workspace
        attach_workspace:
            at: workspace
    - &auth_ssh
        add_ssh_keys:
            fingerprints:
                - "e4:b4:92:9b:6a:57:f5:8a:5d:ee:0a:29:b4:6a:cf:65"
    - &setup_gcp
        run:
          name: Authenticate to GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud config set compute/zone europe-west1-b
            gcloud config set project core-gearbox-112418

job_aliases:
    - &unit
        unit:
            requires:
                - build
    - &e2e
        e2e:
            requires:
                - build
    - &deploy_staging
        deploy_integration_staging:
            requires:
                - e2e
                - unit
            filters:
                branches:
                    only:
                        - staging
    - &deploy_production
        deploy_master:
            requires:
                - e2e
                - unit
            filters:
                branches:
                    only:
                        - master


version: 2.0

jobs:
    build:
        docker:
            - image: passfort/python-builder
        environment:
            - GITHUB_KEY_LOCATION: id_rsa_e4b4929b6a57f58a5dee0a29b46acf65
        steps:
            - checkout
            - *attach_to_workspace
            - *auth_ssh
            - *setup_gcp
            - setup_remote_docker:
                docker_layer_caching:
            - run: |
                pipenv --three
                pipenv install
                pipenv run python deploy.py -bs `cat workspace/integration_name` staging

    lint:
        docker:
            - image: passfort/python-builder
        steps:
            - checkout
            - *attach_to_workspace
            - run:
                name: Check For Error Handling
                command: |
                    cd `cat workspace/integration_name`
                    grep Raven src/*.py || exit 1

    unit:
        docker:
            - image: passfort/python-builder
        steps:
            - checkout
            - *attach_to_workspace
            - *setup_gcp
            - setup_remote_docker:
                docker_layer_caching:
            - run: |
                export INTEGRATION=`cat workspace/integration_name`
                export VERSION=`git cat-file -p HEAD | head -c12 | tail -c7`
                gcloud docker -- pull eu.gcr.io/core-gearbox-112418/integrations-$INTEGRATION:$VERSION
            - run: |
                export INTEGRATION=`cat workspace/integration_name`
                export VERSION=`git cat-file -p HEAD | head -c12 | tail -c7`
                docker run eu.gcr.io/core-gearbox-112418/integrations-$INTEGRATION:$VERSION yarn run unit

    e2e:
        docker:
            - image: passfort/python-builder
        steps:
            - checkout
            - *attach_to_workspace
            - *setup_gcp
            - setup_remote_docker:
                docker_layer_caching:
            - run: |
                export INTEGRATION=`cat workspace/integration_name`
                export VERSION=`git cat-file -p HEAD | head -c12 | tail -c7`
                gcloud docker -- pull eu.gcr.io/core-gearbox-112418/integrations-$INTEGRATION:$VERSION
                docker run --name integration -d eu.gcr.io/core-gearbox-112418/integrations-$INTEGRATION:$VERSION
            - run: docker exec integration yarn run e2e

    deploy_integration_staging:
        docker:
            - image: passfort/python-builder
        steps:
            - checkout
            - *attach_to_workspace
            - *auth_ssh
            - *setup_gcp
            - run: |
                pipenv --three
                pipenv install
                pipenv run python deploy.py -ds `cat workspace/integration_name` staging

    deploy_integration_production:
        docker:
            - image: passfort/python-builder
        steps:
            - checkout
            - *attach_to_workspace
            - *auth_ssh
            - *setup_gcp
            - run: |
                pipenv --three
                pipenv install
                pipenv run python deploy.py -ds `cat workspace/integration_name` production

workflows:
    version: 2
