# coding: utf-8

# flake8: noqa
"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.abstract_audit_details import AbstractAuditDetails
from swagger_client.models.abstract_field import AbstractField
from swagger_client.models.abstract_migration_event_payload import AbstractMigrationEventPayload
from swagger_client.models.abstract_resolution import AbstractResolution
from swagger_client.models.action_detail import ActionDetail
from swagger_client.models.address import Address
from swagger_client.models.associate import Associate
from swagger_client.models.associate_type import AssociateType
from swagger_client.models.audit_entity_type import AuditEntityType
from swagger_client.models.audit_event import AuditEvent
from swagger_client.models.audit_event_action_type import AuditEventActionType
from swagger_client.models.batch_detail import BatchDetail
from swagger_client.models.case_entity_type import CaseEntityType
from swagger_client.models.case_reference import CaseReference
from swagger_client.models.case_screening_state import CaseScreeningState
from swagger_client.models.case_template_response import CaseTemplateResponse
from swagger_client.models.contact_detail import ContactDetail
from swagger_client.models.contact_detail_type import ContactDetailType
from swagger_client.models.country import Country
from swagger_client.models.country_link import CountryLink
from swagger_client.models.country_link_type import CountryLinkType
from swagger_client.models.detail import Detail
from swagger_client.models.detail_type import DetailType
from swagger_client.models.entity import Entity
from swagger_client.models.entity_update_category import EntityUpdateCategory
from swagger_client.models.entity_updated_dates import EntityUpdatedDates
from swagger_client.models.error import Error
from swagger_client.models.event import Event
from swagger_client.models.event_type import EventType
from swagger_client.models.field_result import FieldResult
from swagger_client.models.field_value_type import FieldValueType
from swagger_client.models.file import File
from swagger_client.models.filter import Filter
from swagger_client.models.gender import Gender
from swagger_client.models.group import Group
from swagger_client.models.group_screening_type import GroupScreeningType
from swagger_client.models.identity_document import IdentityDocument
from swagger_client.models.identity_document_location_type import IdentityDocumentLocationType
from swagger_client.models.image import Image
from swagger_client.models.language_code import LanguageCode
from swagger_client.models.lifecycle_state import LifecycleState
from swagger_client.models.match_strength import MatchStrength
from swagger_client.models.migration_audit_action_type import MigrationAuditActionType
from swagger_client.models.name import Name
from swagger_client.models.name_type import NameType
from swagger_client.models.ongoing_screening_update import OngoingScreeningUpdate
from swagger_client.models.organisation_secondary_fields import OrganisationSecondaryFields
from swagger_client.models.pagination import Pagination
from swagger_client.models.passport_check_validity_type import PassportCheckValidityType
from swagger_client.models.profile_action_type import ProfileActionType
from swagger_client.models.profile_entity_type import ProfileEntityType
from swagger_client.models.provider import Provider
from swagger_client.models.provider_source import ProviderSource
from swagger_client.models.provider_source_status import ProviderSourceStatus
from swagger_client.models.provider_source_type import ProviderSourceType
from swagger_client.models.provider_source_type_category_detail import ProviderSourceTypeCategoryDetail
from swagger_client.models.provider_type import ProviderType
from swagger_client.models.resolution_field import ResolutionField
from swagger_client.models.resolution_fields import ResolutionFields
from swagger_client.models.resolution_rules import ResolutionRules
from swagger_client.models.resolution_status_type import ResolutionStatusType
from swagger_client.models.resolution_toolkit_response import ResolutionToolkitResponse
from swagger_client.models.result import Result
from swagger_client.models.result_detail import ResultDetail
from swagger_client.models.results_review_remark import ResultsReviewRemark
from swagger_client.models.review import Review
from swagger_client.models.role import Role
from swagger_client.models.search_response import SearchResponse
from swagger_client.models.secondary_fields_by_entity import SecondaryFieldsByEntity
from swagger_client.models.sort_criterion import SortCriterion
from swagger_client.models.status_rule import StatusRule
from swagger_client.models.status_type import StatusType
from swagger_client.models.subscription_category import SubscriptionCategory
from swagger_client.models.type_available_selected import TypeAvailableSelected
from swagger_client.models.update_case import UpdateCase
from swagger_client.models.user_summary import UserSummary
from swagger_client.models.weblink import Weblink
from swagger_client.models.add_note_to_case_audit_details import AddNoteToCaseAuditDetails
from swagger_client.models.assign_case_to_user_audit_details import AssignCaseToUserAuditDetails
from swagger_client.models.audit_search_response import AuditSearchResponse
from swagger_client.models.change_case_lifecycle_state_audit_details import ChangeCaseLifecycleStateAuditDetails
from swagger_client.models.change_case_screening_state_audit_details import ChangeCaseScreeningStateAuditDetails
from swagger_client.models.country_entity import CountryEntity
from swagger_client.models.edd_request_audit_details import EDDRequestAuditDetails
from swagger_client.models.field import Field
from swagger_client.models.field_definition import FieldDefinition
from swagger_client.models.generic_case_audit_details import GenericCaseAuditDetails
from swagger_client.models.individual_entity import IndividualEntity
from swagger_client.models.migration_event_audit_details import MigrationEventAuditDetails
from swagger_client.models.new_case import NewCase
from swagger_client.models.ongoing_screening_update_search_response import OngoingScreeningUpdateSearchResponse
from swagger_client.models.organisation_entity import OrganisationEntity
from swagger_client.models.provider_detail import ProviderDetail
from swagger_client.models.resolution import Resolution
from swagger_client.models.resolve_results_audit_details import ResolveResultsAuditDetails
from swagger_client.models.results_resolution_action import ResultsResolutionAction
from swagger_client.models.review_results_audit_details import ReviewResultsAuditDetails
from swagger_client.models.screen_case_audit_details import ScreenCaseAuditDetails
from swagger_client.models.secondary_field_result import SecondaryFieldResult
from swagger_client.models.verify_passport_audit_details import VerifyPassportAuditDetails
from swagger_client.models.vessel_entity import VesselEntity
from swagger_client.models.case import Case
from swagger_client.models.case_created_audit_details import CaseCreatedAuditDetails
from swagger_client.models.case_deleted_audit_details import CaseDeletedAuditDetails
from swagger_client.models.case_edited_audit_details import CaseEditedAuditDetails
