# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.migration_audit_action_type import MigrationAuditActionType  # noqa: F401,E501


class AbstractMigrationEventPayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'action_type': 'MigrationAuditActionType',
        'action_date': 'datetime',
        'action_note': 'str',
        'user_name': 'str'
    }

    attribute_map = {
        'action_type': 'actionType',
        'action_date': 'actionDate',
        'action_note': 'actionNote',
        'user_name': 'userName'
    }

    def __init__(self, action_type=None, action_date=None, action_note=None, user_name=None):  # noqa: E501
        """AbstractMigrationEventPayload - a model defined in Swagger"""  # noqa: E501

        self._action_type = None
        self._action_date = None
        self._action_note = None
        self._user_name = None
        self.discriminator = None

        self.action_type = action_type
        self.action_date = action_date
        self.action_note = action_note
        self.user_name = user_name

    @property
    def action_type(self):
        """Gets the action_type of this AbstractMigrationEventPayload.  # noqa: E501


        :return: The action_type of this AbstractMigrationEventPayload.  # noqa: E501
        :rtype: MigrationAuditActionType
        """
        return self._action_type

    @action_type.setter
    def action_type(self, action_type):
        """Sets the action_type of this AbstractMigrationEventPayload.


        :param action_type: The action_type of this AbstractMigrationEventPayload.  # noqa: E501
        :type: MigrationAuditActionType
        """
        if action_type is None:
            raise ValueError("Invalid value for `action_type`, must not be `None`")  # noqa: E501

        self._action_type = action_type

    @property
    def action_date(self):
        """Gets the action_date of this AbstractMigrationEventPayload.  # noqa: E501

        The date and time when the migration event happened.  # noqa: E501

        :return: The action_date of this AbstractMigrationEventPayload.  # noqa: E501
        :rtype: datetime
        """
        return self._action_date

    @action_date.setter
    def action_date(self, action_date):
        """Sets the action_date of this AbstractMigrationEventPayload.

        The date and time when the migration event happened.  # noqa: E501

        :param action_date: The action_date of this AbstractMigrationEventPayload.  # noqa: E501
        :type: datetime
        """
        if action_date is None:
            raise ValueError("Invalid value for `action_date`, must not be `None`")  # noqa: E501

        self._action_date = action_date

    @property
    def action_note(self):
        """Gets the action_note of this AbstractMigrationEventPayload.  # noqa: E501


        :return: The action_note of this AbstractMigrationEventPayload.  # noqa: E501
        :rtype: str
        """
        return self._action_note

    @action_note.setter
    def action_note(self, action_note):
        """Sets the action_note of this AbstractMigrationEventPayload.


        :param action_note: The action_note of this AbstractMigrationEventPayload.  # noqa: E501
        :type: str
        """
        if action_note is None:
            raise ValueError("Invalid value for `action_note`, must not be `None`")  # noqa: E501

        self._action_note = action_note

    @property
    def user_name(self):
        """Gets the user_name of this AbstractMigrationEventPayload.  # noqa: E501


        :return: The user_name of this AbstractMigrationEventPayload.  # noqa: E501
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """Sets the user_name of this AbstractMigrationEventPayload.


        :param user_name: The user_name of this AbstractMigrationEventPayload.  # noqa: E501
        :type: str
        """
        if user_name is None:
            raise ValueError("Invalid value for `user_name`, must not be `None`")  # noqa: E501

        self._user_name = user_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AbstractMigrationEventPayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
