# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AuditEventActionType(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NEW_CASE = "NEW_CASE"
    SCREENED_CASE = "SCREENED_CASE"
    ASSIGN_CASE = "ASSIGN_CASE"
    NEW_MATCH = "NEW_MATCH"
    NEW_NOTE = "NEW_NOTE"
    CHANGE_CASE_OWNER = "CHANGE_CASE_OWNER"
    CHANGE_CASE_LIFECYCLE_STATE = "CHANGE_CASE_LIFECYCLE_STATE"
    CHANGE_CASE_SCREENING_STATE = "CHANGE_CASE_SCREENING_STATE"
    EDITED_CASE = "EDITED_CASE"
    MIGRATION = "MIGRATION"
    REVIEW_RESULT = "REVIEW_RESULT"
    RESOLVE_RESULT = "RESOLVE_RESULT"
    VERIFY_PASSPORT_DETAILS = "VERIFY_PASSPORT_DETAILS"
    EDD_REPORT_REQUESTED_CASE = "EDD_REPORT_REQUESTED_CASE"
    DELETE_CASE = "DELETE_CASE"
    NEW_CLIENT = "NEW_CLIENT"
    NEW_GROUP = "NEW_GROUP"
    UPDATE_GROUP = "UPDATE_GROUP"
    UPDATE_GROUP_STATUS = "UPDATE_GROUP_STATUS"
    UPDATE_CLIENT_STATUS = "UPDATE_CLIENT_STATUS"
    DELETE_GROUP = "DELETE_GROUP"
    UPDATE_GROUP_MEMBERSHIP = "UPDATE_GROUP_MEMBERSHIP"
    UPDATE_GROUP_AUTO_RESOLUTION = "UPDATE_GROUP_AUTO_RESOLUTION"
    UPDATE_GROUP_CUSTOM_FIELDS = "UPDATE_GROUP_CUSTOM_FIELDS"
    UPDATE_GROUP_RESOLUTION_TOOLKIT = "UPDATE_GROUP_RESOLUTION_TOOLKIT"
    UPDATE_GROUP_TIMEZONE = "UPDATE_GROUP_TIMEZONE"
    UPDATE_GROUP_EMAIL_SCHEDULE = "UPDATE_GROUP_EMAIL_SCHEDULE"
    UPDATE_CLIENT_SETTINGS = "UPDATE_CLIENT_SETTINGS"
    UPDATE_GROUP_SUBSCRIPTION_SETTINGS = "UPDATE_GROUP_SUBSCRIPTION_SETTINGS"
    UPDATE_GROUP_SCREENING_SETTINGS = "UPDATE_GROUP_SCREENING_SETTINGS"
    UPDATE_GROUP_PRODUCT_ENTITLEMENTS = "UPDATE_GROUP_PRODUCT_ENTITLEMENTS"
    CREATE_ROLE = "CREATE_ROLE"
    UPDATE_ROLE = "UPDATE_ROLE"
    NEW_USER = "NEW_USER"
    UPDATE_USER = "UPDATE_USER"
    UPDATE_USER_ROLES = "UPDATE_USER_ROLES"
    UPDATE_USER_MEMBERSHIP = "UPDATE_USER_MEMBERSHIP"
    UPDATE_USER_STATUS = "UPDATE_USER_STATUS"
    DELETE_USER = "DELETE_USER"

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
    }

    attribute_map = {
    }

    def __init__(self):  # noqa: E501
        """AuditEventActionType - a model defined in Swagger"""  # noqa: E501
        self.discriminator = None

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuditEventActionType):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
