# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.audit_event import AuditEvent  # noqa: F401,E501
from swagger_client.models.pagination import Pagination  # noqa: F401,E501
from swagger_client.models.search_response import SearchResponse  # noqa: F401,E501
from swagger_client.models.sort_criterion import SortCriterion  # noqa: F401,E501


class AuditSearchResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'sort': 'list[SortCriterion]',
        'pagination': 'Pagination',
        'total_result_count': 'int',
        'results': 'list[AuditEvent]'
    }

    attribute_map = {
        'query': 'query',
        'sort': 'sort',
        'pagination': 'pagination',
        'total_result_count': 'totalResultCount',
        'results': 'results'
    }

    def __init__(self, query=None, sort=None, pagination=None, total_result_count=None, results=None):  # noqa: E501
        """AuditSearchResponse - a model defined in Swagger"""  # noqa: E501

        self._query = None
        self._sort = None
        self._pagination = None
        self._total_result_count = None
        self._results = None
        self.discriminator = None

        if query is not None:
            self.query = query
        if sort is not None:
            self.sort = sort
        if pagination is not None:
            self.pagination = pagination
        self.total_result_count = total_result_count
        if results is not None:
            self.results = results

    @property
    def query(self):
        """Gets the query of this AuditSearchResponse.  # noqa: E501


        :return: The query of this AuditSearchResponse.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this AuditSearchResponse.


        :param query: The query of this AuditSearchResponse.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def sort(self):
        """Gets the sort of this AuditSearchResponse.  # noqa: E501

        The sort critieria to apply to the query  # noqa: E501

        :return: The sort of this AuditSearchResponse.  # noqa: E501
        :rtype: list[SortCriterion]
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this AuditSearchResponse.

        The sort critieria to apply to the query  # noqa: E501

        :param sort: The sort of this AuditSearchResponse.  # noqa: E501
        :type: list[SortCriterion]
        """

        self._sort = sort

    @property
    def pagination(self):
        """Gets the pagination of this AuditSearchResponse.  # noqa: E501


        :return: The pagination of this AuditSearchResponse.  # noqa: E501
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this AuditSearchResponse.


        :param pagination: The pagination of this AuditSearchResponse.  # noqa: E501
        :type: Pagination
        """

        self._pagination = pagination

    @property
    def total_result_count(self):
        """Gets the total_result_count of this AuditSearchResponse.  # noqa: E501


        :return: The total_result_count of this AuditSearchResponse.  # noqa: E501
        :rtype: int
        """
        return self._total_result_count

    @total_result_count.setter
    def total_result_count(self, total_result_count):
        """Sets the total_result_count of this AuditSearchResponse.


        :param total_result_count: The total_result_count of this AuditSearchResponse.  # noqa: E501
        :type: int
        """
        if total_result_count is None:
            raise ValueError("Invalid value for `total_result_count`, must not be `None`")  # noqa: E501

        self._total_result_count = total_result_count

    @property
    def results(self):
        """Gets the results of this AuditSearchResponse.  # noqa: E501


        :return: The results of this AuditSearchResponse.  # noqa: E501
        :rtype: list[AuditEvent]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this AuditSearchResponse.


        :param results: The results of this AuditSearchResponse.  # noqa: E501
        :type: list[AuditEvent]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuditSearchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
