# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.abstract_field import AbstractField  # noqa: F401,E501


class Field(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type_id': 'str',
        'value': 'str',
        'date_time_value': 'datetime'
    }

    attribute_map = {
        'type_id': 'typeId',
        'value': 'value',
        'date_time_value': 'dateTimeValue'
    }

    def __init__(self, type_id=None, value=None, date_time_value=None):  # noqa: E501
        """Field - a model defined in Swagger"""  # noqa: E501

        self._type_id = None
        self._value = None
        self._date_time_value = None
        self.discriminator = None

        self.type_id = type_id
        if value is not None:
            self.value = value
        if date_time_value is not None:
            self.date_time_value = date_time_value

    @property
    def type_id(self):
        """Gets the type_id of this Field.  # noqa: E501

        Type Identifier of this Field  # noqa: E501

        :return: The type_id of this Field.  # noqa: E501
        :rtype: str
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this Field.

        Type Identifier of this Field  # noqa: E501

        :param type_id: The type_id of this Field.  # noqa: E501
        :type: str
        """
        if type_id is None:
            raise ValueError("Invalid value for `type_id`, must not be `None`")  # noqa: E501
        if type_id is not None and len(type_id) > 255:
            raise ValueError("Invalid value for `type_id`, length must be less than or equal to `255`")  # noqa: E501

        self._type_id = type_id

    @property
    def value(self):
        """Gets the value of this Field.  # noqa: E501

        Value for this Field. To be used for fields with [FieldValueType] (#FieldValueType) other than `DATE`.  # noqa: E501

        :return: The value of this Field.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Field.

        Value for this Field. To be used for fields with [FieldValueType] (#FieldValueType) other than `DATE`.  # noqa: E501

        :param value: The value of this Field.  # noqa: E501
        :type: str
        """
        if value is not None and len(value) > 1000:
            raise ValueError("Invalid value for `value`, length must be less than or equal to `1000`")  # noqa: E501

        self._value = value

    @property
    def date_time_value(self):
        """Gets the date_time_value of this Field.  # noqa: E501

        DateTime value for this Field. To be used for fields with [FieldValueType] (#FieldValueType) `DATE`.  # noqa: E501

        :return: The date_time_value of this Field.  # noqa: E501
        :rtype: datetime
        """
        return self._date_time_value

    @date_time_value.setter
    def date_time_value(self, date_time_value):
        """Sets the date_time_value of this Field.

        DateTime value for this Field. To be used for fields with [FieldValueType] (#FieldValueType) `DATE`.  # noqa: E501

        :param date_time_value: The date_time_value of this Field.  # noqa: E501
        :type: datetime
        """

        self._date_time_value = date_time_value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Field):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
