# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.pagination import Pagination  # noqa: F401,E501
from swagger_client.models.sort_criterion import SortCriterion  # noqa: F401,E501


class Filter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'query': 'str',
        'sort': 'list[SortCriterion]',
        'pagination': 'Pagination'
    }

    attribute_map = {
        'query': 'query',
        'sort': 'sort',
        'pagination': 'pagination'
    }

    def __init__(self, query=None, sort=None, pagination=None):  # noqa: E501
        """Filter - a model defined in Swagger"""  # noqa: E501

        self._query = None
        self._sort = None
        self._pagination = None
        self.discriminator = None

        if query is not None:
            self.query = query
        if sort is not None:
            self.sort = sort
        if pagination is not None:
            self.pagination = pagination

    @property
    def query(self):
        """Gets the query of this Filter.  # noqa: E501

        A query filter expression, which is written in a superset of the Atom Feed Item Query Language (FIQL).  The FIQL is documented in <https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00>, and the superset supported by the WC1 API documented in <https://github.com/jirutka/rsql-parser>.   # noqa: E501

        :return: The query of this Filter.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this Filter.

        A query filter expression, which is written in a superset of the Atom Feed Item Query Language (FIQL).  The FIQL is documented in <https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00>, and the superset supported by the WC1 API documented in <https://github.com/jirutka/rsql-parser>.   # noqa: E501

        :param query: The query of this Filter.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def sort(self):
        """Gets the sort of this Filter.  # noqa: E501

        The sort critieria to apply to the query  # noqa: E501

        :return: The sort of this Filter.  # noqa: E501
        :rtype: list[SortCriterion]
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this Filter.

        The sort critieria to apply to the query  # noqa: E501

        :param sort: The sort of this Filter.  # noqa: E501
        :type: list[SortCriterion]
        """

        self._sort = sort

    @property
    def pagination(self):
        """Gets the pagination of this Filter.  # noqa: E501


        :return: The pagination of this Filter.  # noqa: E501
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this Filter.


        :param pagination: The pagination of this Filter.  # noqa: E501
        :type: Pagination
        """

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Filter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
