# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.action_detail import ActionDetail  # noqa: F401,E501
from swagger_client.models.address import Address  # noqa: F401,E501
from swagger_client.models.associate import Associate  # noqa: F401,E501
from swagger_client.models.contact_detail import ContactDetail  # noqa: F401,E501
from swagger_client.models.country_link import CountryLink  # noqa: F401,E501
from swagger_client.models.detail import Detail  # noqa: F401,E501
from swagger_client.models.entity import Entity  # noqa: F401,E501
from swagger_client.models.entity_update_category import EntityUpdateCategory  # noqa: F401,E501
from swagger_client.models.entity_updated_dates import EntityUpdatedDates  # noqa: F401,E501
from swagger_client.models.event import Event  # noqa: F401,E501
from swagger_client.models.file import File  # noqa: F401,E501
from swagger_client.models.gender import Gender  # noqa: F401,E501
from swagger_client.models.identity_document import IdentityDocument  # noqa: F401,E501
from swagger_client.models.image import Image  # noqa: F401,E501
from swagger_client.models.name import Name  # noqa: F401,E501
from swagger_client.models.profile_entity_type import ProfileEntityType  # noqa: F401,E501
from swagger_client.models.provider import Provider  # noqa: F401,E501
from swagger_client.models.provider_source import ProviderSource  # noqa: F401,E501
from swagger_client.models.role import Role  # noqa: F401,E501
from swagger_client.models.weblink import Weblink  # noqa: F401,E501


class IndividualEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'age': 'str',
        'age_as_of_date': 'datetime',
        'events': 'list[Event]',
        'gender': 'Gender',
        'is_deceased': 'bool',
        'previous_roles': 'list[Role]',
        'roles': 'list[Role]'
    }

    attribute_map = {
        'age': 'age',
        'age_as_of_date': 'ageAsOfDate',
        'events': 'events',
        'gender': 'gender',
        'is_deceased': 'isDeceased',
        'previous_roles': 'previousRoles',
        'roles': 'roles'
    }

    def __init__(self, age=None, age_as_of_date=None, events=None, gender=None, is_deceased=False, previous_roles=None, roles=None):  # noqa: E501
        """IndividualEntity - a model defined in Swagger"""  # noqa: E501

        self._age = None
        self._age_as_of_date = None
        self._events = None
        self._gender = None
        self._is_deceased = None
        self._previous_roles = None
        self._roles = None
        self.discriminator = None

        if age is not None:
            self.age = age
        if age_as_of_date is not None:
            self.age_as_of_date = age_as_of_date
        if events is not None:
            self.events = events
        if gender is not None:
            self.gender = gender
        if is_deceased is not None:
            self.is_deceased = is_deceased
        if previous_roles is not None:
            self.previous_roles = previous_roles
        if roles is not None:
            self.roles = roles

    @property
    def age(self):
        """Gets the age of this IndividualEntity.  # noqa: E501


        :return: The age of this IndividualEntity.  # noqa: E501
        :rtype: str
        """
        return self._age

    @age.setter
    def age(self, age):
        """Sets the age of this IndividualEntity.


        :param age: The age of this IndividualEntity.  # noqa: E501
        :type: str
        """

        self._age = age

    @property
    def age_as_of_date(self):
        """Gets the age_as_of_date of this IndividualEntity.  # noqa: E501


        :return: The age_as_of_date of this IndividualEntity.  # noqa: E501
        :rtype: datetime
        """
        return self._age_as_of_date

    @age_as_of_date.setter
    def age_as_of_date(self, age_as_of_date):
        """Sets the age_as_of_date of this IndividualEntity.


        :param age_as_of_date: The age_as_of_date of this IndividualEntity.  # noqa: E501
        :type: datetime
        """

        self._age_as_of_date = age_as_of_date

    @property
    def events(self):
        """Gets the events of this IndividualEntity.  # noqa: E501


        :return: The events of this IndividualEntity.  # noqa: E501
        :rtype: list[Event]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this IndividualEntity.


        :param events: The events of this IndividualEntity.  # noqa: E501
        :type: list[Event]
        """

        self._events = events

    @property
    def gender(self):
        """Gets the gender of this IndividualEntity.  # noqa: E501


        :return: The gender of this IndividualEntity.  # noqa: E501
        :rtype: Gender
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """Sets the gender of this IndividualEntity.


        :param gender: The gender of this IndividualEntity.  # noqa: E501
        :type: Gender
        """

        self._gender = gender

    @property
    def is_deceased(self):
        """Gets the is_deceased of this IndividualEntity.  # noqa: E501


        :return: The is_deceased of this IndividualEntity.  # noqa: E501
        :rtype: bool
        """
        return self._is_deceased

    @is_deceased.setter
    def is_deceased(self, is_deceased):
        """Sets the is_deceased of this IndividualEntity.


        :param is_deceased: The is_deceased of this IndividualEntity.  # noqa: E501
        :type: bool
        """

        self._is_deceased = is_deceased

    @property
    def previous_roles(self):
        """Gets the previous_roles of this IndividualEntity.  # noqa: E501


        :return: The previous_roles of this IndividualEntity.  # noqa: E501
        :rtype: list[Role]
        """
        return self._previous_roles

    @previous_roles.setter
    def previous_roles(self, previous_roles):
        """Sets the previous_roles of this IndividualEntity.


        :param previous_roles: The previous_roles of this IndividualEntity.  # noqa: E501
        :type: list[Role]
        """

        self._previous_roles = previous_roles

    @property
    def roles(self):
        """Gets the roles of this IndividualEntity.  # noqa: E501


        :return: The roles of this IndividualEntity.  # noqa: E501
        :rtype: list[Role]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this IndividualEntity.


        :param roles: The roles of this IndividualEntity.  # noqa: E501
        :type: list[Role]
        """

        self._roles = roles

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IndividualEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
