# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.abstract_audit_details import AbstractAuditDetails  # noqa: F401,E501
from swagger_client.models.abstract_migration_event_payload import AbstractMigrationEventPayload  # noqa: F401,E501


class MigrationEventAuditDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'case_system_id': 'str',
        'action_logs': 'list[AbstractMigrationEventPayload]'
    }

    attribute_map = {
        'case_system_id': 'caseSystemId',
        'action_logs': 'actionLogs'
    }

    def __init__(self, case_system_id=None, action_logs=None):  # noqa: E501
        """MigrationEventAuditDetails - a model defined in Swagger"""  # noqa: E501

        self._case_system_id = None
        self._action_logs = None
        self.discriminator = None

        if case_system_id is not None:
            self.case_system_id = case_system_id
        if action_logs is not None:
            self.action_logs = action_logs

    @property
    def case_system_id(self):
        """Gets the case_system_id of this MigrationEventAuditDetails.  # noqa: E501

        System generated ID for the Case  # noqa: E501

        :return: The case_system_id of this MigrationEventAuditDetails.  # noqa: E501
        :rtype: str
        """
        return self._case_system_id

    @case_system_id.setter
    def case_system_id(self, case_system_id):
        """Sets the case_system_id of this MigrationEventAuditDetails.

        System generated ID for the Case  # noqa: E501

        :param case_system_id: The case_system_id of this MigrationEventAuditDetails.  # noqa: E501
        :type: str
        """

        self._case_system_id = case_system_id

    @property
    def action_logs(self):
        """Gets the action_logs of this MigrationEventAuditDetails.  # noqa: E501


        :return: The action_logs of this MigrationEventAuditDetails.  # noqa: E501
        :rtype: list[AbstractMigrationEventPayload]
        """
        return self._action_logs

    @action_logs.setter
    def action_logs(self, action_logs):
        """Sets the action_logs of this MigrationEventAuditDetails.


        :param action_logs: The action_logs of this MigrationEventAuditDetails.  # noqa: E501
        :type: list[AbstractMigrationEventPayload]
        """

        self._action_logs = action_logs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MigrationEventAuditDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
