# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.provider import Provider  # noqa: F401,E501
from swagger_client.models.provider_source import ProviderSource  # noqa: F401,E501


class ProviderDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'code': 'str',
        'identifier': 'str',
        'master': 'bool',
        'name': 'str',
        'sources': 'list[ProviderSource]'
    }

    attribute_map = {
        'code': 'code',
        'identifier': 'identifier',
        'master': 'master',
        'name': 'name',
        'sources': 'sources'
    }

    def __init__(self, code=None, identifier=None, master=False, name=None, sources=None):  # noqa: E501
        """ProviderDetail - a model defined in Swagger"""  # noqa: E501

        self._code = None
        self._identifier = None
        self._master = None
        self._name = None
        self._sources = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if identifier is not None:
            self.identifier = identifier
        if master is not None:
            self.master = master
        if name is not None:
            self.name = name
        if sources is not None:
            self.sources = sources

    @property
    def code(self):
        """Gets the code of this ProviderDetail.  # noqa: E501


        :return: The code of this ProviderDetail.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ProviderDetail.


        :param code: The code of this ProviderDetail.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def identifier(self):
        """Gets the identifier of this ProviderDetail.  # noqa: E501


        :return: The identifier of this ProviderDetail.  # noqa: E501
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this ProviderDetail.


        :param identifier: The identifier of this ProviderDetail.  # noqa: E501
        :type: str
        """

        self._identifier = identifier

    @property
    def master(self):
        """Gets the master of this ProviderDetail.  # noqa: E501


        :return: The master of this ProviderDetail.  # noqa: E501
        :rtype: bool
        """
        return self._master

    @master.setter
    def master(self, master):
        """Sets the master of this ProviderDetail.


        :param master: The master of this ProviderDetail.  # noqa: E501
        :type: bool
        """

        self._master = master

    @property
    def name(self):
        """Gets the name of this ProviderDetail.  # noqa: E501


        :return: The name of this ProviderDetail.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ProviderDetail.


        :param name: The name of this ProviderDetail.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def sources(self):
        """Gets the sources of this ProviderDetail.  # noqa: E501

        Sources that belong to this provider.  # noqa: E501

        :return: The sources of this ProviderDetail.  # noqa: E501
        :rtype: list[ProviderSource]
        """
        return self._sources

    @sources.setter
    def sources(self, sources):
        """Sets the sources of this ProviderDetail.

        Sources that belong to this provider.  # noqa: E501

        :param sources: The sources of this ProviderDetail.  # noqa: E501
        :type: list[ProviderSource]
        """

        self._sources = sources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProviderDetail):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
