# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.resolution_field import ResolutionField  # noqa: F401,E501


class ResolutionFields(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'statuses': 'list[ResolutionField]',
        'risks': 'list[ResolutionField]',
        'reasons': 'list[ResolutionField]'
    }

    attribute_map = {
        'statuses': 'statuses',
        'risks': 'risks',
        'reasons': 'reasons'
    }

    def __init__(self, statuses=None, risks=None, reasons=None):  # noqa: E501
        """ResolutionFields - a model defined in Swagger"""  # noqa: E501

        self._statuses = None
        self._risks = None
        self._reasons = None
        self.discriminator = None

        self.statuses = statuses
        self.risks = risks
        self.reasons = reasons

    @property
    def statuses(self):
        """Gets the statuses of this ResolutionFields.  # noqa: E501


        :return: The statuses of this ResolutionFields.  # noqa: E501
        :rtype: list[ResolutionField]
        """
        return self._statuses

    @statuses.setter
    def statuses(self, statuses):
        """Sets the statuses of this ResolutionFields.


        :param statuses: The statuses of this ResolutionFields.  # noqa: E501
        :type: list[ResolutionField]
        """
        if statuses is None:
            raise ValueError("Invalid value for `statuses`, must not be `None`")  # noqa: E501

        self._statuses = statuses

    @property
    def risks(self):
        """Gets the risks of this ResolutionFields.  # noqa: E501


        :return: The risks of this ResolutionFields.  # noqa: E501
        :rtype: list[ResolutionField]
        """
        return self._risks

    @risks.setter
    def risks(self, risks):
        """Sets the risks of this ResolutionFields.


        :param risks: The risks of this ResolutionFields.  # noqa: E501
        :type: list[ResolutionField]
        """
        if risks is None:
            raise ValueError("Invalid value for `risks`, must not be `None`")  # noqa: E501

        self._risks = risks

    @property
    def reasons(self):
        """Gets the reasons of this ResolutionFields.  # noqa: E501


        :return: The reasons of this ResolutionFields.  # noqa: E501
        :rtype: list[ResolutionField]
        """
        return self._reasons

    @reasons.setter
    def reasons(self, reasons):
        """Sets the reasons of this ResolutionFields.


        :param reasons: The reasons of this ResolutionFields.  # noqa: E501
        :type: list[ResolutionField]
        """
        if reasons is None:
            raise ValueError("Invalid value for `reasons`, must not be `None`")  # noqa: E501

        self._reasons = reasons

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResolutionFields):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
