# coding: utf-8

"""
    Thomson Reuters World-Check One API

    The World-Check One API enables developers to integrate the next generation of Thomson Reuters screening capabilities into existing workflows and internal systems (such as CRMs) in order to help streamline the processes for on-boarding, KYC and third party due diligence. The API provides, among other features: - The ability to screen entity names, with or without secondary fields such as date of birth for individuals. These names are called “cases” within the World-Check One system. - The ability to retrieve results of the screening process from the World-Check database - The ability to flag cases for Ongoing Screening, and retrieve the World-Check results from the Ongoing Screening process. > © 2017 Thomson Reuters. All rights reserved. Republication or redistribution of Thomson Reuters content, including by framing or similar means, is prohibited without the prior written consent of Thomson Reuters. 'Thomson Reuters' and the Thomson Reuters logo are registered trademarks and trademarks of Thomson Reuters and its affiliated companies.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: Thomson-FCR.PS@Thomsonreuters.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.provider_source import ProviderSource  # noqa: F401,E501


class Role(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end': 'str',
        'location': 'str',
        'source': 'ProviderSource',
        'start': 'str',
        'title': 'str',
        'type': 'str'
    }

    attribute_map = {
        'end': 'end',
        'location': 'location',
        'source': 'source',
        'start': 'start',
        'title': 'title',
        'type': 'type'
    }

    def __init__(self, end=None, location=None, source=None, start=None, title=None, type=None):  # noqa: E501
        """Role - a model defined in Swagger"""  # noqa: E501

        self._end = None
        self._location = None
        self._source = None
        self._start = None
        self._title = None
        self._type = None
        self.discriminator = None

        if end is not None:
            self.end = end
        if location is not None:
            self.location = location
        if source is not None:
            self.source = source
        if start is not None:
            self.start = start
        if title is not None:
            self.title = title
        if type is not None:
            self.type = type

    @property
    def end(self):
        """Gets the end of this Role.  # noqa: E501


        :return: The end of this Role.  # noqa: E501
        :rtype: str
        """
        return self._end

    @end.setter
    def end(self, end):
        """Sets the end of this Role.


        :param end: The end of this Role.  # noqa: E501
        :type: str
        """

        self._end = end

    @property
    def location(self):
        """Gets the location of this Role.  # noqa: E501


        :return: The location of this Role.  # noqa: E501
        :rtype: str
        """
        return self._location

    @location.setter
    def location(self, location):
        """Sets the location of this Role.


        :param location: The location of this Role.  # noqa: E501
        :type: str
        """

        self._location = location

    @property
    def source(self):
        """Gets the source of this Role.  # noqa: E501


        :return: The source of this Role.  # noqa: E501
        :rtype: ProviderSource
        """
        return self._source

    @source.setter
    def source(self, source):
        """Sets the source of this Role.


        :param source: The source of this Role.  # noqa: E501
        :type: ProviderSource
        """

        self._source = source

    @property
    def start(self):
        """Gets the start of this Role.  # noqa: E501


        :return: The start of this Role.  # noqa: E501
        :rtype: str
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this Role.


        :param start: The start of this Role.  # noqa: E501
        :type: str
        """

        self._start = start

    @property
    def title(self):
        """Gets the title of this Role.  # noqa: E501


        :return: The title of this Role.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this Role.


        :param title: The title of this Role.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """Gets the type of this Role.  # noqa: E501


        :return: The type of this Role.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Role.


        :param type: The type of this Role.  # noqa: E501
        :type: str
        """

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Role):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
