#!/bin/sh -i
echo $COVERAGE_FILE
COVERAGE_FILE=/tmp/coverage_e2e pipenv run coverage run --branch --omit='e2e/*','**/test_*' --source . main.py &

# Waiting for the server to start
sleep 5

# Launch the e2e tests
yarn e2e

# Send SIGINT to all jobs to ask the server process to gracefully shutdown
kill -INT $(jobs -p)

# Wait for the .coverage file
while [ ! -f /tmp/coverage_e2e ]; do sleep 1; done

# Convert coverage report to XML
pipenv run coverage xml -i

if [ -z "$INTEGRATION" ]; then
    integration_name=${PWD##*/}
else
    integration_name=$INTEGRATION
fi

# We need to prepend the integration_name so that codecov can succesfully
# match the coverage data with the files in the integrations monorepo
sed -i "s/filename=\"/filename=\"${integration_name}\//g" /tmp/coverage_e2e
