_nationalities = {
    "afghan": "AFG",
    "albanian": "ALB",
    "algerian": "DZA",
    "american": "USA",
    "andorran": "AND",
    "angolan": "AGO",
    "antiguan": "ATG",
    "argentinean": "ARG",
    "armenian": "ARM",
    "australian": "AUS",
    "austrian": "AUT",
    "azerbaijani": "AZE",
    "bahamian": "BHS",
    "bahraini": "BHR",
    "bangladeshi": "BGD",
    "barbadian": "BRB",
    "belarusian": "BLR",
    "belgian": "BEL",
    "belizian": "BLZ",
    "beninese": "BEN",
    "bhutanese": "BTN",
    "bolivian": "BOL",
    "bosnian": "BIH",
    "batswana": "BWA",
    "brazilian": "BRA",
    "british": "GBR",
    "bulgarian": "BGR",
    "burkinabe": "BFA",
    "burmese": "MMR",
    "burundian": "BDI",
    "Cape verdean": "CPV",
    "cambodian": "KHM",
    "cameroonian": "CMR",
    "canadian": "CAN",
    "central african": "CAF",
    "chadian": "TCD",
    "chilean": "CHL",
    "chinese": "CHN",
    "colombian": "COL",
    "comoran": "COM",
    "congolese": "COG",
    "costa rican": "CRI",
    "croatian": "HRV",
    "cuban": "CUB",
    "cypriot": "CYP",
    "czech": "CZE",
    "danish": "DNK",
    "djibouti": "DJI",
    "dominican": "DOM",
    "dutch": "NLD",
    "East timorese": "TLS",
    "ecuadorean": "ECU",
    "egyptian": "EGY",
    "emirian": "ARE",
    "equatorial guinean": "GNQ",
    "eritrean": "ERI",
    "estonian": "EST",
    "ethiopian": "ETH",
    "fijian": "FJI",
    "filipino": "PHL",
    "finnish": "FIN",
    "french": "FRA",
    "french guianese": "GUF",
    "french polynesian": "PYF",
    "gabonese": "GAB",
    "gambian": "GMB",
    "georgian": "GEO",
    "german": "DEU",
    "ghanaian": "GHA",
    "greek": "GRC",
    "grenadian": "GRD",
    "guatemalan": "GTM",
    "guinean": "GIN",
    "guinea-bissauan": "GNB",
    "guyanese": "GUY",
    "haitian": "HTI",
    "herzegovinian": "BIH",
    "holy see": "VAT",
    "honduran": "HND",
    "hungarian": "HUN",
    "icelander": "ISL",
    "indian": "IND",
    "indonesian": "IDN",
    "ivorian": "CIV",
    "iranian": "IRN",
    "iraqi": "IRQ",
    "irish": "IRL",
    "israeli": "ISR",
    "italian": "ITA",
    "jamaican": "JAM",
    "japanese": "JPN",
    "jordanian": "JOR",
    "kazakhstani": "KAZ",
    "kenyan": "KEN",
    "kittian and nevisian": "KNA",
    "i-kiribati": "KIR",
    "kuwaiti": "KWT",
    "kyrgyz": "KGZ",
    "laotian": "LAO",
    "latvian": "LVA",
    "lebanese": "LBN",
    "liberian": "LBR",
    "libyan": "LBY",
    "liechtensteiner": "LIE",
    "lithuanian": "LTU",
    "luxembourger": "LUX",
    "macedonian": "MKD",
    "malagasy": "MDG",
    "malawian": "MWI",
    "malaysian": "MYS",
    "maldivan": "MDV",
    "malian": "MLI",
    "maltese": "MLT",
    "marshallese": "MHL",
    "mauritanian": "MRT",
    "mauritian": "MUS",
    "mexican": "MEX",
    "micronesian": "FSM",
    "moldovan": "MDA",
    "monacan": "MCO",
    "mongolian": "MNG",
    "montenegro": "MNE",
    "montserrat": "MSR",
    "morocco": "MAR",
    "mosotho": "LSO",
    "mozambican": "MOZ",
    "namibian": "NAM",
    "nauruan": "NRU",
    "nepalese": "NPL",
    "new caledonia": "NCL",
    "new zealander": "NZL",
    "ni-vanuatu": "VUT",
    "nicaraguan": "NIC",
    "nigerian": "NGA",
    "nigerien": "NER",
    "north korean": "PRK",
    "norwegian": "NOR",
    "omani": "OMN",
    "pakistani": "PAK",
    "palauan": "PLW",
    "palestinian": "PSE",
    "panamanian": "PAN",
    "papua New guinean": "PNG",
    "paraguayan": "PRY",
    "peruvian": "PER",
    "polish": "POL",
    "portuguese": "PRT",
    "qatari": "QAT",
    "romanian": "ROU",
    "russian": "RUS",
    "rwandan": "RWA",
    "saint lucian": "LCA",
    "salvadoran": "SLV",
    "samoan": "WSM",
    "san marinese": "SMR",
    "sao tomean": "STP",
    "saudi": "SAU",
    "senegalese": "SEN",
    "serbian": "SRB",
    "seychellois": "SYC",
    "sierra leonean": "SLE",
    "singaporean": "SGP",
    "slovakian": "SVK",
    "slovenian": "SVN",
    "solomon islander": "SLB",
    "somali": "SOM",
    "south african": "ZAF",
    "south korean": "KOR",
    "spanish": "ESP",
    "sri lankan": "LKA",
    "sudanese": "SDN",
    "surinamer": "SUR",
    "swazi": "SWZ",
    "swedish": "SWE",
    "swiss": "CHE",
    "syrian": "SYR",
    "taiwanese": "TWN",
    "tajik": "TJK",
    "tanzanian": "TZA",
    "thai": "THA",
    "togolese": "TGO",
    "tongan": "TON",
    "trinidadian": "TTO",
    "tobagonian": "TTO",
    "tunisian": "TUN",
    "turkish": "TUR",
    "tuvaluan": "TUV",
    "ugandan": "UGA",
    "ukrainian": "UKR",
    "uruguayan": "URY",
    "uzbekistani": "UZB",
    "venezuelan": "VEN",
    "vietnamese": "VNM",
    "yemenite": "YEM",
    "zambian": "ZMB",
    "zimbabwean": "ZWE"
}


def convert_nationality_to_iso3(nationality, default=None):
    return _nationalities.get(nationality.lower(), default)
