#!/bin/sh -i
pipenv run coverage run --branch --omit='e2e/*','**/test_*' --source . main.py &

# Waiting for the server to start
sleep 5

# Launch the e2e tests
yarn e2e
test_return_value=$?

# Send SIGINT to all jobs to ask the server process to gracefully shutdown
kill -INT $(jobs -p)

if [ $test_return_value -ne 0 ]; then
     echo "Return code was not zero but $test_return_value"
     exit 1
fi

# Wait for the .coverage file
while [ ! -f .coverage ]; do sleep 1; done

# Convert coverage report to XML
pipenv run coverage xml -i

if [ -z "$INTEGRATION" ]; then
    integration_name=${PWD##*/}
else
    integration_name=$INTEGRATION
fi

# We need to prepend the integration_name so that codecov can succesfully
# match the coverage data with the files in the integrations monorepo
sed -i "s/filename=\"/filename=\"${integration_name}\//g" coverage.xml

if [ -z "$CODECOV_TOKEN" ]; then
    echo "Will not upload code coverage to codecov"
    cat coverage.xml
else
    pipenv run codecov -F $integration_name -X search -f coverage.xml
fi
