#!/bin/sh

integration_name="creditsafe"

pipenv run coverage run --source=app --omit=./**/test_** --branch -m unittest discover . && \
pipenv run coverage xml -i && \

sed -i "s/filename=\"/filename=\"${integration_name}\//g" coverage.xml && \

pipenv run codecov -F ${integration_name} -X search -f coverage.xml